apiVersion: apps/v1
kind: Deployment
metadata:
  name: donetick-frontend
  namespace: donetick
  labels:
    app.kubernetes.io/name: donetick-frontend
    app.kubernetes.io/part-of: donetick
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: donetick-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: donetick-frontend
        app.kubernetes.io/part-of: donetick
    spec:
      containers:
        - name: donetick-frontend
          image: forgejo.lab.themalinconicos.com/brian/donetick-frontend:38451eb2678c26e3928f4e306eb622c794d2e0ba
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
