apiVersion: v1
kind: Service
metadata:
  name: donetick-frontend
  namespace: donetick
  labels:
    app.kubernetes.io/name: donetick-frontend
    app.kubernetes.io/part-of: donetick
spec:
  selector:
    app.kubernetes.io/name: donetick-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
